### ISSUE TITLE
Add Game option

### ISSUE THREAD

**Issue by ghost** [Scorpeg/Button-Swap#1]
Add an option for this config: 

```
*all
ux0:tai/buttonswap.suprx
```

for select what game who will be swap :D

**Comment by adlogic** [comment]
What option? It never intended to be for all, if you want for all - use xyz homebrew https://github.com/xyzz/vita-button-swapper

**Comment by adlogic** [comment]
Explain what do you want to do. I see no sense in using *ALL here.

**Comment by Scorpeg** [comment]
I see no sense in using *ALL here. Whole point is to make it activated individually only for needed titles. And by me using config.txt is much better rather than using weird key combinations every time or similar.

**Comment by fennectech** [comment]
I think they mean   so that if *all is used it will ask weather you want to swap on a per title basis  (wich i would actually like)

**Comment by fennectech** [comment]
basicly   when you laungh title  it asks you weahter you want to swap or not

**Comment by Scorpeg** [comment]
Just do not use *all. It is built to swap only on certain titles. What you suggest here would require one more separate listing of all titles affected with this method, which would result in 2 different ways of settings. So unless there would be more than 10 request for this exact feature I do not plan to implement it.

**Comment by fennectech** [comment]
okay sounds good   we need a tool to build out the list of installed title id's

**Comment by Scorpeg** [comment]
Even if I can code that, it would be better if someone made a GUI tool for config.txt on Vita. This would be useful, while just list of installed title id's would be not really useful (as you can just go in ux0:app and see them/copy-paste).

**Comment by fennectech** [comment]
right   but a tool that lists title ids  and the human title of the game i mean
