### ISSUE TITLE
Doesnt work in save menu

### ISSUE THREAD

**Issue by fennectech** [Scorpeg/Button-Swap#2]
when a game uses the livearea save tool it does not work in that menu.

**Comment by Scorpeg** [comment]
Of course, as this is intended behavior. If you have for example layout "X to confirm" in system and have a game "O to confirm" and swap buttons in game - it would result in having "X to confirm" in system and "X to confirm" in game, so all would be smoothly integrated. And if swap these too - you will get "O to confirm" in livearea save, which is completely unneeded.

This is why livearea save do not swap.

**Comment by fennectech** [comment]
Ah  okay   Makes sense    Thanks for the plugin    Makes  games alot more painless   Its far less annoying than the game being like that lol
